Document: npapiheaders
Title: Debian npapiheaders Manual
Author: <insert document author here>
Abstract: This manual describes what npapiheaders is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/npapiheaders/npapiheaders.sgml.gz

Format: postscript
Files: /usr/share/doc/npapiheaders/npapiheaders.ps.gz

Format: text
Files: /usr/share/doc/npapiheaders/npapiheaders.text.gz

Format: HTML
Index: /usr/share/doc/npapiheaders/html/index.html
Files: /usr/share/doc/npapiheaders/html/*.html
